"""Inference and metric callbacks used by the Gradio interface."""

from __future__ import annotations

import tempfile
import time
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import gradio as gr
import pandas as pd
import torch
from PIL import Image

from app.deep_learning.alignment import align_reconstruction_to_target
from app.deep_learning.fsrcnn import fsrcnn_upsample
from app.deep_learning.imdn import imdn_upsample
from app.evaluation.images import bicubic_downsample, bicubic_upsample
from app.evaluation.metrics import calculate_quality_metrics
from app.fusion.back_projection import back_projection_fusion
from app.traditional.nedi import nedi_upsample_rgb
from demo.runtime import device, load_fsrcnn, load_imdn
from demo.settings import (
    DIRECT_LR_MODE,
    EXAMPLES_ROOT,
    EXPERIMENT_MODE,
    MAX_LR_SIDE,
    NEDI_CONFIG,
    SCALES,
)


@dataclass(frozen=True)
class MethodOutput:
    image: Image.Image
    seconds: float
    notes: str


@dataclass(frozen=True)
class PreparedInput:
    image: Image.Image
    original_size: tuple[int, int]
    resized: bool


def get_presets() -> list[list[Any]]:
    presets = []
    if (EXAMPLES_ROOT / "geometric_lr.png").exists():
        presets.append([
            str(EXAMPLES_ROOT / "geometric_lr.png"),
            2,
            DIRECT_LR_MODE,
            str(EXAMPLES_ROOT / "geometric_hr.png"),
        ])
    if (EXAMPLES_ROOT / "concentric_lr.png").exists():
        presets.append([
            str(EXAMPLES_ROOT / "concentric_lr.png"),
            2,
            DIRECT_LR_MODE,
            str(EXAMPLES_ROOT / "concentric_hr.png"),
        ])
    if (EXAMPLES_ROOT / "lattice_lr.png").exists():
        presets.append([
            str(EXAMPLES_ROOT / "lattice_lr.png"),
            2,
            DIRECT_LR_MODE,
            str(EXAMPLES_ROOT / "lattice_hr.png"),
        ])
    return presets


def clean_image(image: Image.Image) -> Image.Image:
    return image.convert("RGB")


def target_size(lr_image: Image.Image, scale: int) -> tuple[int, int]:
    return (lr_image.width * scale, lr_image.height * scale)


def resize_for_demo(lr_image: Image.Image) -> PreparedInput:
    largest_side = max(lr_image.size)
    if largest_side <= MAX_LR_SIDE:
        return PreparedInput(
            image=lr_image,
            original_size=lr_image.size,
            resized=False,
        )

    ratio = MAX_LR_SIDE / largest_side
    resized_size = (
        max(1, round(lr_image.width * ratio)),
        max(1, round(lr_image.height * ratio)),
    )
    resized = lr_image.resize(resized_size, Image.Resampling.BICUBIC)
    return PreparedInput(
        image=resized,
        original_size=lr_image.size,
        resized=True,
    )


def resize_note(prepared: PreparedInput) -> str | None:
    if not prepared.resized:
        return None
    old_width, old_height = prepared.original_size
    new_width, new_height = prepared.image.size
    return (
        f"Input resized from {old_width}x{old_height}px to "
        f"{new_width}x{new_height}px for demo speed."
    )


def prepare_experiment_input(
    hr_image: Image.Image,
    scale: int,
) -> tuple[Image.Image, Image.Image, str]:
    source_hr = clean_image(hr_image)
    notes = [
        "Experiment-style mode: uploaded image treated as HR reference; LR was generated by bicubic downsampling."
    ]

    largest_lr_side = max(source_hr.size) / scale
    if largest_lr_side > MAX_LR_SIDE:
        ratio = (MAX_LR_SIDE * scale) / max(source_hr.size)
        resized_size = (
            max(scale, round(source_hr.width * ratio)),
            max(scale, round(source_hr.height * ratio)),
        )
        source_hr = source_hr.resize(resized_size, Image.Resampling.BICUBIC)
        notes.append(
            f"HR display reference resized from {hr_image.width}x{hr_image.height}px "
            f"to {source_hr.width}x{source_hr.height}px so generated LR stays within {MAX_LR_SIDE}px."
        )

    aligned_hr, lr_image = bicubic_downsample(source_hr, scale)
    if aligned_hr.size != source_hr.size:
        notes.append(
            f"HR reference trimmed to {aligned_hr.width}x{aligned_hr.height}px "
            f"so dimensions divide cleanly by x{scale}."
        )

    notes.append(f"Generated LR size: {lr_image.width}x{lr_image.height}px.")
    return lr_image, aligned_hr, " ".join(notes)


def time_call(function: Any, *args: Any) -> MethodOutput:
    start = time.perf_counter()
    image, notes = function(*args)
    return MethodOutput(image=image, seconds=time.perf_counter() - start, notes=notes)


def run_bicubic(lr_image: Image.Image, scale: int) -> tuple[Image.Image, str]:
    return bicubic_upsample(lr_image, target_size(lr_image, scale)), "Bicubic"


def run_nedi(lr_image: Image.Image, scale: int) -> tuple[Image.Image, str]:
    result = nedi_upsample_rgb(lr_image, scale, target_size(lr_image, scale), NEDI_CONFIG)
    return result.image, f"NEDI ({result.native_passes} pass)"


def run_fsrcnn(lr_image: Image.Image, scale: int, inference_device: torch.device) -> tuple[Image.Image, str]:
    try:
        model = load_fsrcnn(scale, str(inference_device))
        native = fsrcnn_upsample(model, lr_image, inference_device)
        result = align_reconstruction_to_target(native, target_size(lr_image, scale))
        return result.image, "FSRCNN (12.8K)"
    except Exception as exc:
        fallback = bicubic_upsample(lr_image, target_size(lr_image, scale))
        return fallback, f"FSRCNN (Unavailable: {exc})"


def run_imdn(lr_image: Image.Image, scale: int, inference_device: torch.device) -> tuple[Image.Image, str]:
    try:
        model = load_imdn(scale, str(inference_device))
        native = imdn_upsample(model, lr_image, inference_device)
        result = align_reconstruction_to_target(native, target_size(lr_image, scale))
        return result.image, "IMDN (703K)"
    except Exception as exc:
        fallback = bicubic_upsample(lr_image, target_size(lr_image, scale))
        return fallback, f"IMDN (Unavailable: {exc})"


def metric_row(
    method: str,
    output: MethodOutput,
    reference_hr: Image.Image | None,
    scale: int,
) -> dict[str, str | float]:
    row: dict[str, str | float] = {
        "Method": method,
        "PSNR-Y": "—",
        "SSIM-Y": "—",
        "Latency": f"{output.seconds:.3f}s",
        "Notes": output.notes,
    }
    if reference_hr is not None and reference_hr.size == output.image.size:
        metrics = calculate_quality_metrics(reference_hr, output.image, border=scale)
        row["PSNR-Y"] = f"{metrics['psnr_y']:.2f} dB"
        row["SSIM-Y"] = f"{metrics['ssim_y']:.4f}"
    return row


def save_zip(outputs: dict[str, MethodOutput], scale: int) -> str:
    temp_file = tempfile.NamedTemporaryFile(prefix=f"sr_x{scale}_", suffix=".zip", delete=False)
    temp_path = Path(temp_file.name)
    temp_file.close()
    with zipfile.ZipFile(temp_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name, out in outputs.items():
            img_path = temp_path.with_name(f"{name}_x{scale}.png")
            out.image.save(img_path)
            archive.write(img_path, arcname=f"{name}_x{scale}.png")
            img_path.unlink(missing_ok=True)
    return str(temp_path)


def run_super_resolution(
    input_image: Image.Image | None,
    scale: int,
    input_mode: str,
    reference_hr: Image.Image | None,
) -> tuple[
    tuple[Image.Image, Image.Image] | None,
    Image.Image | None,
    Image.Image | None,
    Image.Image | None,
    Image.Image | None,
    Image.Image | None,
    pd.DataFrame,
    str | None,
    dict[str, Image.Image],
]:
    if input_image is None:
        raise gr.Error("Upload an image first.")

    scale = int(scale)
    if scale not in SCALES:
        raise gr.Error(f"Scale must be one of {SCALES}.")

    setup_note: str | None = None
    demo_resize_note: str | None = None

    if input_mode == EXPERIMENT_MODE:
        lr_image, reference, setup_note = prepare_experiment_input(input_image, scale)
    else:
        prepared = resize_for_demo(clean_image(input_image))
        lr_image = prepared.image
        reference = (
            clean_image(reference_hr)
            if reference_hr is not None and not prepared.resized
            else None
        )
        demo_resize_note = resize_note(prepared)

    inference_device = device()

    bicubic = time_call(run_bicubic, lr_image, scale)
    nedi = time_call(run_nedi, lr_image, scale)
    fsrcnn = time_call(run_fsrcnn, lr_image, scale, inference_device)
    imdn = time_call(run_imdn, lr_image, scale, inference_device)

    fusion_start = time.perf_counter()
    fusion_res = back_projection_fusion(lr_image, nedi.image, imdn.image)
    fusion = MethodOutput(
        image=fusion_res.image,
        seconds=time.perf_counter() - fusion_start,
        notes=f"Fusion (IMDN {fusion_res.imdn_weight:.2f}, NEDI {fusion_res.nedi_weight:.2f})",
    )

    outputs = {
        "bicubic": bicubic,
        "nedi": nedi,
        "fsrcnn": fsrcnn,
        "imdn": imdn,
        "fusion": fusion,
    }

    records = [metric_row(k.upper(), v, reference, scale) for k, v in outputs.items()]
    df = pd.DataFrame(records)
    zip_path = save_zip(outputs, scale)

    output_size = target_size(lr_image, scale)
    image_store = {
        "lr": lr_image.resize(output_size, Image.Resampling.NEAREST),
        "bicubic": bicubic.image,
        "nedi": nedi.image,
        "fsrcnn": fsrcnn.image,
        "imdn": imdn.image,
        "fusion": fusion.image,
    }
    slider = (bicubic.image, imdn.image)

    if setup_note is not None:
        df.loc[len(df)] = {
            "Method": "SETUP",
            "PSNR-Y": "—",
            "SSIM-Y": "—",
            "Latency": "—",
            "Notes": setup_note,
        }

    if demo_resize_note is not None:
        df.loc[len(df)] = {
            "Method": "DEMO",
            "PSNR-Y": "—",
            "SSIM-Y": "—",
            "Latency": "—",
            "Notes": f"{demo_resize_note} PSNR/SSIM disabled because the LR input was resized.",
        }

    return (
        slider,
        bicubic.image,
        nedi.image,
        fsrcnn.image,
        imdn.image,
        fusion.image,
        df,
        zip_path,
        image_store,
    )


def update_slider(pair: str, store: dict[str, Image.Image] | None) -> tuple[Image.Image, Image.Image] | None:
    if not store:
        return None
    if "LR" in pair:
        return (store.get("lr", store["bicubic"]), store["imdn"])
    if "NEDI" in pair:
        return (store["nedi"], store["imdn"])
    if "FSRCNN" in pair:
        return (store["fsrcnn"], store["imdn"])
    return (store["bicubic"], store["imdn"])
